version: '3'

# ---------------------
networks:
  # 1. netmain
  netmain:
    driver: bridge

# ---------------------     
services:
  # 1. frontface
  frontface:
      image: ${PROJECT}_frontface
      tty: true      
      expose:
        - "8000"    
      ports:
        - "8000:8000"
      networks:
        - netmain
      environment:
        - PROJECT=frontface
        - WORKON_HOME=/frontface/.env
        - PYTHONPATH=/frontface
        # ..
        - CONFIGURATION=dev
        - HOST=localhost  
        - PORT=8000
      volumes:
        - ../image/src:/frontface
        - ../image/runserv.sh:/usr/local/bin/runserv.sh
      # .............................................        
      command: /bin/bash