version: '3'

networks:
# ---------------------
  netmain:
    driver: bridge
   
services:
# ---------------------  
  frontface:
      image: ${PROJECT}_frontface
      tty: true      
      expose:
        - "8000"    
      ports:
        - "8000:8000"
      networks:
        - netmain
      environment:
        - PROJECT=${PROJECT}
        - WORKON_HOME=/${PROJECT}/.env
        - PYTHONPATH=/${PROJECT}
        # ...
      volumes:
        - ../../image/src:/${PROJECT}
        - ../../image/runserv.sh:/usr/local/bin/runserv.sh
        - ../../image/data:/data
      # .............................................        
      command: /bin/bash